name: benchmarks

on:
  workflow_dispatch:
  # push:
  #   branches: [ "master" ]

env:
  MAINNET_EXECUTION_RPC: ${{ secrets.MAINNET_EXECUTION_RPC }}
  SEPOLIA_EXECUTION_RPC: ${{ secrets.SEPOLIA_EXECUTION_RPC }}

jobs:
  benches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install repository Rust toolchain
        run: rustup toolchain install --profile minimal --component rustfmt
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: bench --package helios
